import {
  Home,
  CalendarMonth,
  ShoppingCart,
  Assignment,
  MenuBook,
  Settings,
  HeadsetMic,
  HelpOutline,
  Person,
  PowerSettingsNew,
  AccessTime,
  FavoriteBorder,
  Favorite,
  Search,
  ArrowBack,
  FilterList,
  Delete,
  Send,
  ExpandMore,
  ChevronLeft,
  ChevronRight,
} from '@mui/icons-material';

export const icons = {
  home: <Home />,
  mealPlanner: <CalendarMonth />,
  shoppingCart: <ShoppingCart />,
  shoppingList: <Assignment />,
  book: <MenuBook />,
  settings: <Settings />,
  support: <HeadsetMic />,
  help: <HelpOutline />,
  person: <Person />,
  logout: <PowerSettingsNew />,
  clock: <AccessTime />,
  heart: <FavoriteBorder />,
  heartFilled: <Favorite />,
  search: <Search />,
  filter: <FilterList />,
  arrowBack: <ArrowBack />,
  delete: <Delete />,
  send: <Send />,
  expandMore: <ExpandMore />,
  arrowLeft: <ChevronLeft />,
  arrowRight: <ChevronRight />,
};
