version: '2.4'
services:
  backend:
    image: node:16-alpine
    working_dir: /app
    command: sh -c "npx knex migrate:latest && npx knex seed:run && npm run start:dev"
    user: node
    volumes:
      - ./:/app:cached
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_URL=${DB_URL}
      - ACCESS_TOKEN_KEY=${ACCESS_TOKEN_KEY}
      - ACCESS_TOKEN_EXPIRATION_TIME=${ACCESS_TOKEN_EXPIRATION_TIME}
      - S3_BUCKET=${S3_BUCKET}
      - S3_REGION=${S3_REGION}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
    depends_on:
      - postgres
    ports:
      - 5000:5000
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin4_container
  #   restart: always
  #   ports:
  #     - '5050:80'
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
  #   depends_on:
  #     - postgres
